### ISSUE TITLE
catSeq和catSeqTG的效果为什么这么接近，无论是否使用2RF_1？

### ISSUE THREAD

**Issue by love2poppy** [kenchan0226/keyphrase-generation-rl#1]
TG-Net论文里的结果是TG-Net明显比CopyRNN要高，消融实验里给的是超过一个点。是否是TG-net不适用于catSeq这种结构？

**Comment by kenchan0226** [comment]
我的理解是，在catSeq 這種結構，CopyRNN 已經達到一個比較好的效果，添加其他module (e.g., title guided encoder, coverage attention, etc.) 並不能為它帶來significant 的提升。

**Comment by love2poppy** [comment]
> 我的理解是，在catSeq 這種結構，CopyRNN 已經達到一個比較好的效果，添加其他module (e.g., title guided encoder, coverage mechanism, etc.) 並不能為它帶來significant 的提升。

应该是这么一回事了，感谢你的回答
