### ISSUE TITLE
Inquiry about experiment results

### ISSUE THREAD

**Issue by LeaLiLu** [kenchan0226/keyphrase-generation-rl#11]
Hi,
As mentioned in your paper that you used **Macro**-averaged scores, and the reported experiment results of present keyphrase prediction of **catSeqD**  model on kp20k dataset is **0.285** (F1@5 metric) .
![image](https://user-images.githubusercontent.com/24774195/71883538-97703480-3171-11ea-9c75-cd04f66d9ad8.png)

When I ran the catSeqD model with your code, I got a similar **Macro**-averaged  score with you of  **0.286**  on the metric of  F1@5, and the **Micro**-averaged score of **0.270**.
![image](https://user-images.githubusercontent.com/24774195/71883739-fc2b8f00-3171-11ea-80bd-f0369612ae69.png)

But according the results reported in the paper _One Size Does Not Fit All: Generating and Evaluating Variable Number of Keyphrases_ [https://arxiv.org/abs/1810.05241](url)
It seems that they used the **Micro**-averaged score.
![image](https://user-images.githubusercontent.com/24774195/71884907-2d0cc380-3174-11ea-8599-fd5a94aa7e42.png)

And they got the score of **0.348** of **catSeqD** model on the metric of  F1@5.
![image](https://user-images.githubusercontent.com/24774195/71884984-588fae00-3174-11ea-8e04-561bd5ced9c3.png)

I am confused about the different results of the same model on the same dataset.
Is there anything wrong with this comparison ?

**Comment by kenchan0226** [comment]
As mentioned in Section 6.2 of our paper, the implementation of F1@5 in our paper is different from Yuan et al. 2018. See the below screenshot for the reason. 
![image](https://user-images.githubusercontent.com/4735503/71885969-59294400-3176-11ea-90be-71e949cabab2.png)

**Comment by LeaLiLu** [comment]
Thanks!
