### ISSUE TITLE
issue about rl training

### ISSUE THREAD

**Issue by Xiao0728** [kenchan0226/keyphrase-generation-rl#13]
Hi,
I have completed the ML training on my own dataset using Catseq and CatseqD model. And when I started RL training based on the trained ML model, it will report the following issue, could you help me out there? what might be the causes of this problem? Thanks a lot.

04/13/2020 23:09:17 [ERROR] train: message
Traceback (most recent call last):
  File "train.py", line 166, in main
    train_rl.train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loader, opt)
  File "/keyphrase-generation-rl-master/train_rl.py", line 69, in train_model
    batch_reward_stat, log_selected_token_dist = train_one_batch(batch, generator, optimizer_rl, opt, perturb_std)
  File "/keyphrase-generation-rl-master/train_rl.py", line 200, in train_one_batch
    src_str_list, opt.separate_present_absent, pykp.io.PEOS_WORD)
  File "/keyphrase-generation-rl-master/pykp/reward.py", line 13, in sample_list_to_str_2dlist
    word_list = prediction_to_sentence(sample['prediction'], idx2word, vocab_size, oov, eos_idx, unk_idx, replace_unk, src_word_list, sample['attention'])
  File "/keyphrase-generation-rl-master/utils/string_helper.py", line 28, in prediction_to_sentence
    word = idx2word[_pred]
KeyError: 40284

**Comment by kenchan0226** [comment]
Hi, it seems that your model generates a token that does not present in the idx2word dictionary, did you use our preprocess.py to generate the `vocab.pt`  of your dataset, and specify the option `-vocab` to the correct directory?

**Comment by Xiao0728** [comment]
Hi Kenchan,
Thanks for your quick reply. Yes, I have preprocessed and generated `vocab.pt` and specify the path correctly. Is there any possibility that the punctuation in the target file causes this problem? I didn't remove the punctuation in my target file.
Xiao

**Comment by kenchan0226** [comment]
Hi, I think punctuation will not cause this problem. If the target file has punctuations, the punctuations will be stored in the word2idx and idx2word dictionary. 
Can you wrap the `word = idx2word[_pred]` using a try except block, and print out the idx that causes the error?

**Comment by Xiao0728** [comment]
Hi Kenchan, 
I printed out the idx  causes the error, some of them are as following:
`/anaconda3/envs/kpRL/lib/python3.6/site-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  "num_layers={}".form
at(dropout, num_layers))
Epoch 1; batch: 0; total batch: 0
29915
31153
36730
`
How should I deal with these words?

**Comment by kenchan0226** [comment]
This is weird. The vocabulary size should be >50k and it should cover these indices. 
Can you run the train_rl.py again and print out the length of word2idx and idx2word? If the lengths are smaller than 50k, than there is a problem when loading the word2idx and idx2word. If you can also check if this problem occurs during RL training.

**Comment by Xiao0728** [comment]
Hi,
I have checked the length of the `word2idx` and `idx2word` of my dataset after in `preprocess.py`, the length is : 
`
(kpRL) bash-4.2$ python3 preprocess.py -data_dir data/msQ2Q -remove_eos -include_peos
2008 rows filtered
length of word2idx is: 28168
length of word2idx is: 28168
`
So the lengths are smaller than 50k(i.e. the opt.vocab_size). 
This problem only occurred during RL training, and it's ok for ML training. Do you think where could I change to make RL training also suitable for this dataset?
Thanks for your reply!
Xiao

**Comment by kenchan0226** [comment]
Both RL training and ML training use the same line of code (line 157 in train.py) and call the load_data_and_vocab function from in utils/dataloader.py to load the word2idx, can you try to set a breakpoint to see if the word2idx are different in ml training and rl training?

**Comment by Xiao0728** [comment]
No, the length of the word2idx for ml training and rl training are the same. I mean, the problem here might be, It works fine when the vocab size of the dataset is larger than the designated `op.vocab_size=50,002` , but would be an error when smaller than that. 

for my dataset, the generated vocab.pt is 28168, which is smaller than op.vocab_size set as 50002. 
I checked the 'train.ml`, it didn't use this `op.vocab_size`, but the `train.rl` has designated and used this `op.vocab_size`. Thus it can perform ML training, and become error while RL training.
The `op.vocab_size` is set as 50,002 is to select the top 50,000 frequency words as the vocabulary for the decoder. 



So I tried to config the `op.vocab_size=20,000`, it still cann't work, error as: 
```
RuntimeError: Error(s) in loading state_dict for Seq2SeqModel:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([50002, 100]) from checkpoint, the shape in current model is torch.Size([20000, 100]).
        size mismatch for decoder.embedding.weight: copying a param with shape torch.Size([50002, 100]) from checkpoint, the shape in current model is torch.Size([20000, 100]).
        size mismatch for decoder.vocab_dist_linear_2.weight: copying a param with shape torch.Size([50002, 300]) from checkpoint, the shape in current model is torch.Size([20000, 300]).
        size mismatch for decoder.vocab_dist_linear_2.bias: copying a param with shape torch.Size([50002]) from checkpoint, the shape in current model is torch.Size([20000]).
```

**Comment by kenchan0226** [comment]
Hi, only change the vocab_size in RL training will not work since it will try to load state dict from your ml pretrained model with 50k vocab size. Thus, it shows the size mismatch error. 
For your case, I think it is better to set a smaller vocab size (e.g., 28k) from the preprocessing, ml training and rl training. Then it should work.

**Comment by Xiao0728** [comment]
Yes, you are right. Thanks very much. 
And another question I wanna know is, does this framework can also work using Glove embedding like using Glove in OpenNMT?

**Comment by kenchan0226** [comment]
Yes, I think this framework also work if you load the weights from the pretrained Glove embedding and continue to fine-tune the embedding end-to-end.

**Comment by Xiao0728** [comment]
Excellent, thanks a lot!

**Comment by Xiao0728** [comment]
Hi, Kenchan,
I used the floowing command to use the pre-trained embedding to train the model, could you help me to check if it is right to use?
I have generated the Glove pretrained embedding, then when I submitted to train a catseq ML model using this cmd (Question1: I was wondering, since we have designated the `-pre_word_vecs_enc` and `-pre_word_vecs_dec`, why do we still need to specify the dataset path`-data` ?
```
python3 train.py -data data/kp20k/ -vocab data/kp20k/ -pre_word_vecs_enc "data/kp20k/embeddings.enc.pt" -pre_word_vecs_dec "data/kp20k/embeddings.dec.pt" 
-exp_path exp/%s.%s -exp kp20k -epochs 20 -copy_attention -train_ml -one2many -one2many_mode 1 -batch_size 12 -separate_present_absent -seed 9527

Question2: I'm kind of confused about whether RL training based on the ML pre-trained model needs to specify the options: `-pre_word_vecs_enc` and `-pre_word_vecs_dec`.

Thanks in advance.
Xiao
