### ISSUE TITLE
About number of generated keyphrases

### ISSUE THREAD

**Issue by RandomTuringDuck** [kenchan0226/keyphrase-generation-rl#14]
关于您论文里的模型生成关键词数量的实验结果，有些地方我不是很明白，想要请教一下
 
![](https://user-images.githubusercontent.com/13444256/80094483-e57e3c00-8598-11ea-892d-96c5cc881681.png)
![](https://user-images.githubusercontent.com/13444256/80094671-4148c500-8599-11ea-8f12-65813124ae5e.png)

1. 关于oracle那一行，Avg #present 的2.837是统计的整个数据集，还是训练集，验证集，或是测试集？那如果是整个数据集的话，包含了训练集岂不是不太合理- -，因为感觉模型用训练集训练，再用训练集生成结果？
2. 还有表中的众模型的结果是基于验证集还是测试集？包括MAE和平均数量。那统计过程中是去掉重复的关键词，还是未去重？
3. 另外在ACL2020的一篇文章里《Exclusive Hierarchical Decoding for Deep Keyphrase Generation》他统计的oracle Avg #present =3.32，但是他也没有说这是基于整个数据集还是仅仅是测试集或验证集的统计结果。我自己统计了一下测试集和验证集Avg #present都是在3.4左右，比较接近ACL2020这篇文章。

希望得到您的建议

**Comment by kenchan0226** [comment]
1. These are the results on the testing set.
2. We remove all the duplicated keyphrases before computing the MAE and avg # keyphrases. They are the results on the testing set.
3. The results of Exclusive Hierarchical Decoding for Deep Keyphrase Generation are also on the testing set, but Wang Chen may used a different way to preprocess the data in this paper. @Chen-Wang-CUHK , can you help to explain this question? Thanks.

**Comment by Chen-Wang-CUHK** [comment]
> 1. These are the results on the testing set.
> 2. We remove all the duplicated keyphrases before computing the MAE and avg # keyphrases. They are the results on the testing set.
> 3. The results of Exclusive Hierarchical Decoding for Deep Keyphrase Generation are also on the testing set, but Wang Chen may used a different way to preprocess the data in this paper. @Chen-Wang-CUHK , can you help to explain this question? Thanks.

In the ACL 2019 paper, we do not stem the source input and keyphrases when we compute the number of present and absent keyphrases. But in the ACL 2020 paper, we stem them before we compute the statistics.

**Comment by RandomTuringDuck** [comment]
> 1. These are the results on the testing set.
> 2. We remove all the duplicated keyphrases before computing the MAE and avg # keyphrases. They are the results on the testing set.
> 3. The results of Exclusive Hierarchical Decoding for Deep Keyphrase Generation are also on the testing set, but Wang Chen may used a different way to preprocess the data in this paper. @Chen-Wang-CUHK , can you help to explain this question? Thanks.

非常感谢您的解答

**Comment by RandomTuringDuck** [comment]
> > 1. These are the results on the testing set.
> > 2. We remove all the duplicated keyphrases before computing the MAE and avg # keyphrases. They are the results on the testing set.
> > 3. The results of Exclusive Hierarchical Decoding for Deep Keyphrase Generation are also on the testing set, but Wang Chen may used a different way to preprocess the data in this paper. @Chen-Wang-CUHK , can you help to explain this question? Thanks.
> 
> In the ACL 2019 paper, we do not stem the source input and keyphrases when we compute the number of present and absent keyphrases. But in the ACL 2020 paper, we stem them before we compute the statistics.

原来是这样呀，我明白了，非常感谢
