### ISSUE TITLE
how to perform adaptive reward in RL training？

### ISSUE THREAD

**Issue by johncs999** [kenchan0226/keyphrase-generation-rl#17]
Hi, kenchan, thanks for your codes! I am confusing how to use adaptive reward in RL training as in your paper. 
I find using `-reward_type 7` equals to use F1 all the time and is not adaptive, do I misunderstand sth. ?

**Comment by kenchan0226** [comment]
Hi John, the adaptive part is controlled by the topk argument in line 137 of `reward.py`. In the training command, we set the argument of topk to be `G`. 
The code is actually quite confusing. In the `compute_classification_metrics_at_k` function of `evaluate_prediction.py`, if the number of predicted keyprhases is less than the target, it will set topk to the number of ground-truth keyphrases (line 334, 335). Then, the variable `num_predictions_k` will be set to the number of ground-truth keyphrases (line 348). In this case, the result of precision will be the same as recall. And the result of F1 score will be the same as recall as well.

**Comment by johncs999** [comment]
Thanks for your kind reply.
