### ISSUE TITLE
about the semeval dataset

### ISSUE THREAD

**Issue by jiacheng-ye** [kenchan0226/keyphrase-generation-rl#18]
Hi, kenchan, I notice that the semeval test file is different from the others (e.g. they are already stemmed.) How to get the unstemmed version ?

**Comment by kenchan0226** [comment]
Hi, for the unstemmed version of SEMEVAL, maybe you can contact the author of the first deep keyphrase generation [paper](https://arxiv.org/pdf/1704.06879.pdf), Rui Meng. You may also check whether his new repository contains the unstemmed version of SEMEVAL, https://github.com/memray/OpenNMT-kpg-release

**Comment by jiacheng-ye** [comment]
Thanks !
