### ISSUE TITLE
The folder 'data/cross_domain_separated/' cannot be found

### ISSUE THREAD

**Issue by iamxpy** [kenchan0226/keyphrase-generation-rl#2]
在Decode from a pretrained model的部分，當我嘗試評估catSeq-2RF1在 inspec 數據集上的表現時，遇到了FileNotFoundError，我仔細檢查了README，仍然沒搞清楚這個文件夾是哪裡來的。請問提供的數據集是否漏了該文件夾？

報錯信息：
`FileNotFoundError: [Errno 2] No such file or directory: 'data/cross_domain_separated/word_inspec_testing_context.txt'`

**Comment by kenchan0226** [comment]
Sorry, I forgot to add the folder "cross_domain_separated" to the zip file of datasets. I have updated it. Please check. Thanks.
