### ISSUE TITLE
Cross Domain Data Target Data

### ISSUE THREAD

**Issue by eesss34690** [kenchan0226/keyphrase-generation-rl#26]
Hi,

I am currently reproducing this experiment, and I am now able to generate the result for kp20k dataset.
As for the cross domain test case, do you have the default answer for them as well? Or is there any misunderstanding about the method of evaluating the result for them?
For kp20k dataset, I use valid_src.txt as the input file for interactive_predict.py. After that, I use the result as the prediction file, valid_src.txt as the test src file, and valid_trg.txt as the target file.
For the case of cross domain test case, there is no valid_trg.txt in the file provided.

**Comment by kenchan0226** [comment]
The `valid_src.txt` and `valid_trg.txt` contain the data samples of the validation set. Please use `test_src.txt` and `test_trg.txt` if you want to generate the results in the test set.

**Comment by eesss34690** [comment]
Hi @kenchan0226 ,
Thank you for the explanation! I have already solved the issue and get the data!
